name: gptkids_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_svg: ^1.1.6
  # flutter_svg: 2.1.0
  image_picker: ^1.0.4
  dio: ^5.4.0
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.0
  webview_flutter: ^4.4.2
  flutter_telegram_login: ^0.0.2
  mask_text_input_formatter: ^2.9.0
  json_annotation: ^4.9.0
  msix: ^3.16.9

# dependencies:
  # json_annotation: ^4.9.0

# dev_dependencies:
  # build_runner: ^2.3.3
  # json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.14
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

msix_config:
  display_name: Gptkids app
  publisher_display_name: LLC Gptkids
  identity_name: com.gptkids.assistant
  certificate_path: msix/gptkids_cert.pfx
  certificate_password: 123456